export const productData = [
    {
        name: 'Bike helmet',
        rarity: 'blue',
        priceDrop: -20,
        link: 'https://kross.pl',
        image: 'https://',
    },
    {
        name: 'Bike',
        rarity: 'purple',
        priceDrop: -999,
        link: 'https://kross.pl',
        image: 'https://',
    },
    {
        name: 'Bike wheel',
        rarity: 'green',
        priceDrop: -5,
        link: 'https://kross.pl',
        image: 'https://',
    },
    {
        name: 'Bike helmet',
        rarity: 'blue',
        priceDrop: -20,
        link: 'https://kross.pl',
        image: 'https://',
    },
    {
        name: 'Bike',
        rarity: 'purple',
        priceDrop: -999,
        link: 'https://kross.pl',
        image: 'https://',
    },
    {
        name: 'Bike wheel',
        rarity: 'green',
        priceDrop: -5,
        link: 'https://kross.pl',
        image: 'https://',
    },
    {
        name: 'Bike helmet',
        rarity: 'blue',
        priceDrop: -20,
        link: 'https://kross.pl',
        image: 'https://',
    },
    {
        name: 'Bike',
        rarity: 'purple',
        priceDrop: -999,
        link: 'https://kross.pl',
        image: 'https://',
    },
    {
        name: 'Bike wheel',
        rarity: 'green',
        priceDrop: -5,
        link: 'https://kross.pl',
        image: 'https://',
    },
    {
        name: 'Bike helmet',
        rarity: 'blue',
        priceDrop: -20,
        link: 'https://kross.pl',
        image: 'https://',
    },
    {
        name: 'Bike',
        rarity: 'purple',
        priceDrop: -999,
        link: 'https://kross.pl',
        image: 'https://',
    },
    {
        name: 'Bike wheel',
        rarity: 'green',
        priceDrop: -5,
        link: 'https://kross.pl',
        image: 'https://',
    },
    {
        name: 'Bike helmet',
        rarity: 'blue',
        priceDrop: -20,
        link: 'https://kross.pl',
        image: 'https://',
    },
    {
        name: 'Bike',
        rarity: 'purple',
        priceDrop: -999,
        link: 'https://kross.pl',
        image: 'https://',
    },
    {
        name: 'Bike wheel',
        rarity: 'green',
        priceDrop: -5,
        link: 'https://kross.pl',
        image: 'https://',
    },
    {
        name: 'Bike helmet',
        rarity: 'blue',
        priceDrop: -20,
        link: 'https://kross.pl',
        image: 'https://',
    },
    {
        name: 'Bike',
        rarity: 'purple',
        priceDrop: -999,
        link: 'https://kross.pl',
        image: 'https://',
    },
    {
        name: 'Bike wheel',
        rarity: 'green',
        priceDrop: -5,
        link: 'https://kross.pl',
        image: 'https://',
    },
    {
        name: 'Bike helmet',
        rarity: 'blue',
        priceDrop: -20,
        link: 'https://kross.pl',
        image: 'https://',
    },
    {
        name: 'Bike',
        rarity: 'purple',
        priceDrop: -999,
        link: 'https://kross.pl',
        image: 'https://',
    },
    {
        name: 'Bike wheel',
        rarity: 'green',
        priceDrop: -5,
        link: 'https://kross.pl',
        image: 'https://',
    },
    {
        name: 'Bike helmet',
        rarity: 'blue',
        priceDrop: -20,
        link: 'https://kross.pl',
        image: 'https://',
    },
    {
        name: 'Bike',
        rarity: 'purple',
        priceDrop: -999,
        link: 'https://kross.pl',
        image: 'https://',
    },
    {
        name: 'Bike wheel',
        rarity: 'green',
        priceDrop: -5,
        link: 'https://kross.pl',
        image: 'https://',
    },
    {
        name: 'Bike helmet',
        rarity: 'blue',
        priceDrop: -20,
        link: 'https://kross.pl',
        image: 'https://',
    },
    {
        name: 'Bike',
        rarity: 'purple',
        priceDrop: -999,
        link: 'https://kross.pl',
        image: 'https://',
    },
    {
        name: 'Bike wheel',
        rarity: 'green',
        priceDrop: -5,
        link: 'https://kross.pl',
        image: 'https://',
    },
    {
        name: 'Bike helmet',
        rarity: 'blue',
        priceDrop: -20,
        link: 'https://kross.pl',
        image: 'https://',
    },
    {
        name: 'Bike',
        rarity: 'purple',
        priceDrop: -999,
        link: 'https://kross.pl',
        image: 'https://',
    },
    {
        name: 'Bike wheel',
        rarity: 'green',
        priceDrop: -5,
        link: 'https://kross.pl',
        image: 'https://',
    },
    {
        name: 'Bike helmet',
        rarity: 'blue',
        priceDrop: -20,
        link: 'https://kross.pl',
        image: 'https://',
    },
    {
        name: 'Bike',
        rarity: 'purple',
        priceDrop: -999,
        link: 'https://kross.pl',
        image: 'https://',
    },
    {
        name: 'Bike wheel',
        rarity: 'green',
        priceDrop: -5,
        link: 'https://kross.pl',
        image: 'https://',
    },
    {
        name: 'Bike helmet',
        rarity: 'blue',
        priceDrop: -20,
        link: 'https://kross.pl',
        image: 'https://',
    },
    {
        name: 'Bike',
        rarity: 'purple',
        priceDrop: -999,
        link: 'https://kross.pl',
        image: 'https://',
    },
    {
        name: 'Bike wheel',
        rarity: 'green',
        priceDrop: -5,
        link: 'https://kross.pl',
        image: 'https://',
    },
    {
        name: 'Bike helmet',
        rarity: 'blue',
        priceDrop: -20,
        link: 'https://kross.pl',
        image: 'https://',
    },
    {
        name: 'Bike',
        rarity: 'purple',
        priceDrop: -999,
        link: 'https://kross.pl',
        image: 'https://',
    },
    {
        name: 'Bike wheel',
        rarity: 'green',
        priceDrop: -5,
        link: 'https://kross.pl',
        image: 'https://',
    },
    {
        name: 'Bike helmet',
        rarity: 'blue',
        priceDrop: -20,
        link: 'https://kross.pl',
        image: 'https://',
    },
    {
        name: 'Bike',
        rarity: 'purple',
        priceDrop: -999,
        link: 'https://kross.pl',
        image: 'https://',
    },
    {
        name: 'Bike wheel',
        rarity: 'green',
        priceDrop: -5,
        link: 'https://kross.pl',
        image: 'https://',
    },
    {
        name: 'Bike helmet',
        rarity: 'blue',
        priceDrop: -20,
        link: 'https://kross.pl',
        image: 'https://',
    },
    {
        name: 'Bike',
        rarity: 'purple',
        priceDrop: -999,
        link: 'https://kross.pl',
        image: 'https://',
    },
    {
        name: 'Bike wheel',
        rarity: 'green',
        priceDrop: -5,
        link: 'https://kross.pl',
        image: 'https://',
    },
    {
        name: 'Bike helmet',
        rarity: 'blue',
        priceDrop: -20,
        link: 'https://kross.pl',
        image: 'https://',
    },
    {
        name: 'Bike',
        rarity: 'purple',
        priceDrop: -999,
        link: 'https://kross.pl',
        image: 'https://',
    },
    {
        name: 'Bike wheel',
        rarity: 'green',
        priceDrop: -5,
        link: 'https://kross.pl',
        image: 'https://',
    },
    {
        name: 'Bike helmet',
        rarity: 'blue',
        priceDrop: -20,
        link: 'https://kross.pl',
        image: 'https://',
    },
    {
        name: 'Bike',
        rarity: 'purple',
        priceDrop: -999,
        link: 'https://kross.pl',
        image: 'https://',
    },
    {
        name: 'Bike wheel',
        rarity: 'green',
        priceDrop: -5,
        link: 'https://kross.pl',
        image: 'https://',
    },
    {
        name: 'Bike helmet',
        rarity: 'blue',
        priceDrop: -20,
        link: 'https://kross.pl',
        image: 'https://',
    },
    {
        name: 'Bike',
        rarity: 'purple',
        priceDrop: -999,
        link: 'https://kross.pl',
        image: 'https://',
    },
    {
        name: 'Bike wheel',
        rarity: 'green',
        priceDrop: -5,
        link: 'https://kross.pl',
        image: 'https://',
    },
    {
        name: 'Bike helmet',
        rarity: 'blue',
        priceDrop: -20,
        link: 'https://kross.pl',
        image: 'https://',
    },
    {
        name: 'Bike',
        rarity: 'purple',
        priceDrop: -999,
        link: 'https://kross.pl',
        image: 'https://',
    },
    {
        name: 'Bike wheel',
        rarity: 'green',
        priceDrop: -5,
        link: 'https://kross.pl',
        image: 'https://',
    },
    {
        name: 'Bike helmet',
        rarity: 'blue',
        priceDrop: -20,
        link: 'https://kross.pl',
        image: 'https://',
    },
    {
        name: 'Bike',
        rarity: 'purple',
        priceDrop: -999,
        link: 'https://kross.pl',
        image: 'https://',
    },
    {
        name: 'Bike wheel',
        rarity: 'green',
        priceDrop: -5,
        link: 'https://kross.pl',
        image: 'https://',
    },
    {
        name: 'Bike helmet',
        rarity: 'blue',
        priceDrop: -20,
        link: 'https://kross.pl',
        image: 'https://',
    },
    {
        name: 'Bike',
        rarity: 'purple',
        priceDrop: -999,
        link: 'https://kross.pl',
        image: 'https://',
    },
    {
        name: 'Bike wheel',
        rarity: 'green',
        priceDrop: -5,
        link: 'https://kross.pl',
        image: 'https://',
    },
    {
        name: 'Bike helmet',
        rarity: 'blue',
        priceDrop: -20,
        link: 'https://kross.pl',
        image: 'https://',
    },
    {
        name: 'Bike',
        rarity: 'purple',
        priceDrop: -999,
        link: 'https://kross.pl',
        image: 'https://',
    },
    {
        name: 'Bike wheel',
        rarity: 'green',
        priceDrop: -5,
        link: 'https://kross.pl',
        image: 'https://',
    },
    {
        name: 'Bike helmet',
        rarity: 'blue',
        priceDrop: -20,
        link: 'https://kross.pl',
        image: 'https://',
    },
    {
        name: 'Bike',
        rarity: 'purple',
        priceDrop: -999,
        link: 'https://kross.pl',
        image: 'https://',
    },
    {
        name: 'Bike wheel',
        rarity: 'green',
        priceDrop: -5,
        link: 'https://kross.pl',
        image: 'https://',
    },
    {
        name: 'Bike helmet',
        rarity: 'blue',
        priceDrop: -20,
        link: 'https://kross.pl',
        image: 'https://',
    },
    {
        name: 'Bike',
        rarity: 'purple',
        priceDrop: -999,
        link: 'https://kross.pl',
        image: 'https://',
    },
    {
        name: 'Bike wheel',
        rarity: 'green',
        priceDrop: -5,
        link: 'https://kross.pl',
        image: 'https://',
    },
]