export const productData = [
    {
        name: 'Bike helmet',
        rarity: 'blue',
        priceDrop: -20,
        link: 'http://kross.pl',
        image: 'http://localhost:3000/assets/prizes/Helmet1.jpg',
    },
    {
        name: 'Bike',
        rarity: 'purple',
        priceDrop: -999,
        link: 'http://kross.pl',
        image: 'http://localhost:3000/assets/prizes/Bike1.jpg',
    },
    {
        name: 'Bike wheel',
        rarity: 'green',
        priceDrop: -5,
        link: 'http://kross.pl',
        image: 'http://localhost:3000/assets/prizes/Wheel2.jpg',
    },
    {
        name: 'Bike helmet',
        rarity: 'blue',
        priceDrop: -20,
        link: 'http://kross.pl',
        image: 'http://localhost:3000/assets/prizes/Helmet2.jpg',
    },
    {
        name: 'Bike',
        rarity: 'purple',
        priceDrop: -999,
        link: 'http://kross.pl',
        image: 'http://localhost:3000/assets/prizes/Bike2.jpg',
    },
    {
        name: 'Bike wheel',
        rarity: 'green',
        priceDrop: -5,
        link: 'http://kross.pl',
        image: 'http://localhost:3000/assets/prizes/Wheel1.jpg',
    },
    {
        name: 'Bike helmet',
        rarity: 'blue',
        priceDrop: -20,
        link: 'http://kross.pl',
        image: 'http://localhost:3000/assets/prizes/Helmet3.jpg',
    },
    {
        name: 'Bike',
        rarity: 'purple',
        priceDrop: -999,
        link: 'http://kross.pl',
        image: 'http://localhost:3000/assets/prizes/Bike3.jpg',
    },
    {
        name: 'Bike wheel',
        rarity: 'green',
        priceDrop: -5,
        link: 'http://kross.pl',
        image: 'http://localhost:3000/assets/prizes/Wheel2.jpg',
    },
    {
        name: 'Bike helmet',
        rarity: 'blue',
        priceDrop: -20,
        link: 'http://kross.pl',
        image: 'http://localhost:3000/assets/prizes/Helmet2.jpg',
    },
    {
        name: 'Bike',
        rarity: 'purple',
        priceDrop: -999,
        link: 'http://kross.pl',
        image: 'http://localhost:3000/assets/prizes/Bike1.jpg',
    },
    {
        name: 'Bike wheel',
        rarity: 'green',
        priceDrop: -5,
        link: 'http://kross.pl',
        image: 'http://localhost:3000/assets/prizes/Wheel1.jpg',
    },
    {
        name: 'Bike helmet',
        rarity: 'blue',
        priceDrop: -20,
        link: 'http://kross.pl',
        image: 'http://localhost:3000/assets/prizes/Helmet2.jpg',
    },
    {
        name: 'Bike',
        rarity: 'purple',
        priceDrop: -999,
        link: 'http://kross.pl',
        image: 'http://localhost:3000/assets/prizes/Bike1.jpg',
    },
    {
        name: 'Bike wheel',
        rarity: 'green',
        priceDrop: -5,
        link: 'http://kross.pl',
        image: 'http://localhost:3000/assets/prizes/Wheel2.jpg',
    },
    {
        name: 'Bike helmet',
        rarity: 'blue',
        priceDrop: -20,
        link: 'http://kross.pl',
        image: 'http://localhost:3000/assets/prizes/Helmet1.jpg',
    },
    {
        name: 'Bike',
        rarity: 'purple',
        priceDrop: -999,
        link: 'http://kross.pl',
        image: 'http://localhost:3000/assets/prizes/Bike1.jpg',
    },
    {
        name: 'Bike wheel',
        rarity: 'green',
        priceDrop: -5,
        link: 'http://kross.pl',
        image: 'http://localhost:3000/assets/prizes/Wheel1.jpg',
    },
    {
        name: 'Bike helmet',
        rarity: 'blue',
        priceDrop: -20,
        link: 'http://kross.pl',
        image: 'http://localhost:3000/assets/prizes/Helmet2.jpg',
    },
    {
        name: 'Bike',
        rarity: 'purple',
        priceDrop: -999,
        link: 'http://kross.pl',
        image: 'http://localhost:3000/assets/prizes/Bike3.jpg',
    },
    {
        name: 'Bike wheel',
        rarity: 'green',
        priceDrop: -5,
        link: 'http://kross.pl',
        image: 'http://localhost:3000/assets/prizes/Wheel2.jpg',
    },
    {
        name: 'Bike helmet',
        rarity: 'blue',
        priceDrop: -20,
        link: 'http://kross.pl',
        image: 'http://localhost:3000/assets/prizes/Helmet2.jpg',
    },
    {
        name: 'Bike',
        rarity: 'purple',
        priceDrop: -999,
        link: 'http://kross.pl',
        image: 'http://localhost:3000/assets/prizes/Bike2.jpg',
    },
    {
        name: 'Bike wheel',
        rarity: 'green',
        priceDrop: -5,
        link: 'http://kross.pl',
        image: 'http://localhost:3000/assets/prizes/Wheel2.jpg',
    },
    {
        name: 'Bike helmet',
        rarity: 'blue',
        priceDrop: -20,
        link: 'http://kross.pl',
        image: 'http://localhost:3000/assets/prizes/Helmet3.jpg',
    },
    {
        name: 'Bike',
        rarity: 'purple',
        priceDrop: -999,
        link: 'http://kross.pl',
        image: 'http://localhost:3000/assets/prizes/Bike3.jpg',
    },
    {
        name: 'Bike wheel',
        rarity: 'green',
        priceDrop: -5,
        link: 'http://kross.pl',
        image: 'http://localhost:3000/assets/prizes/Wheel1.jpg',
    },
    {
        name: 'Bike helmet',
        rarity: 'blue',
        priceDrop: -20,
        link: 'http://kross.pl',
        image: 'http://localhost:3000/assets/prizes/Helmet3.jpg',
    },
    {
        name: 'Bike',
        rarity: 'purple',
        priceDrop: -999,
        link: 'http://kross.pl',
        image: 'http://localhost:3000/assets/prizes/Bike1.jpg',
    },
    {
        name: 'Bike wheel',
        rarity: 'green',
        priceDrop: -5,
        link: 'http://kross.pl',
        image: 'http://localhost:3000/assets/prizes/Wheel1.jpg',
    },
    {
        name: 'Bike helmet',
        rarity: 'blue',
        priceDrop: -20,
        link: 'http://kross.pl',
        image: 'http://localhost:3000/assets/prizes/Helmet3.jpg',
    },
    {
        name: 'Bike',
        rarity: 'purple',
        priceDrop: -999,
        link: 'http://kross.pl',
        image: 'http://localhost:3000/assets/prizes/Bike2.jpg',
    },
    {
        name: 'Bike wheel',
        rarity: 'green',
        priceDrop: -5,
        link: 'http://kross.pl',
        image: 'http://localhost:3000/assets/prizes/Wheel1.jpg',
    },
    {
        name: 'Bike helmet',
        rarity: 'blue',
        priceDrop: -20,
        link: 'http://kross.pl',
        image: 'http://localhost:3000/assets/prizes/Helmet3.jpg',
    },
    {
        name: 'Bike',
        rarity: 'purple',
        priceDrop: -999,
        link: 'http://kross.pl',
        image: 'http://localhost:3000/assets/prizes/Bike1.jpg',
    },
    {
        name: 'Bike wheel',
        rarity: 'green',
        priceDrop: -5,
        link: 'http://kross.pl',
        image: 'http://localhost:3000/assets/prizes/Wheel1.jpg',
    },
    {
        name: 'Bike helmet',
        rarity: 'blue',
        priceDrop: -20,
        link: 'http://kross.pl',
        image: 'http://localhost:3000/assets/prizes/Helmet1.jpg',
    },
    {
        name: 'Bike',
        rarity: 'purple',
        priceDrop: -999,
        link: 'http://kross.pl',
        image: 'http://localhost:3000/assets/prizes/Bike2.jpg',
    },
    {
        name: 'Bike wheel',
        rarity: 'green',
        priceDrop: -5,
        link: 'http://kross.pl',
        image: 'http://localhost:3000/assets/prizes/Wheel2.jpg',
    },
    {
        name: 'Bike helmet',
        rarity: 'blue',
        priceDrop: -20,
        link: 'http://kross.pl',
        image: 'http://localhost:3000/assets/prizes/Helmet3.jpg',
    },
    {
        name: 'Bike',
        rarity: 'purple',
        priceDrop: -999,
        link: 'http://kross.pl',
        image: 'http://localhost:3000/assets/prizes/Bike1.jpg',
    },
    {
        name: 'Bike wheel',
        rarity: 'green',
        priceDrop: -5,
        link: 'http://kross.pl',
        image: 'http://localhost:3000/assets/prizes/Wheel1.jpg',
    },
    {
        name: 'Bike helmet',
        rarity: 'blue',
        priceDrop: -20,
        link: 'http://kross.pl',
        image: 'http://localhost:3000/assets/prizes/Wheel2.jpg',
    },
    {
        name: 'Bike',
        rarity: 'purple',
        priceDrop: -999,
        link: 'http://kross.pl',
        image: 'http://localhost:3000/assets/prizes/Bike3.jpg',
    },
    {
        name: 'Bike wheel',
        rarity: 'green',
        priceDrop: -5,
        link: 'http://kross.pl',
        image: 'http://localhost:3000/assets/prizes/Wheel1.jpg',
    },
    {
        name: 'Bike helmet',
        rarity: 'blue',
        priceDrop: -20,
        link: 'http://kross.pl',
        image: 'http://localhost:3000/assets/prizes/Helmet3.jpg',
    },
    {
        name: 'Bike',
        rarity: 'purple',
        priceDrop: -999,
        link: 'http://kross.pl',
        image: 'http://localhost:3000/assets/prizes/Bike2.jpg',
    },
    {
        name: 'Bike wheel',
        rarity: 'green',
        priceDrop: -5,
        link: 'http://kross.pl',
        image: 'http://localhost:3000/assets/prizes/Wheel2.jpg',
    },
    {
        name: 'Bike helmet',
        rarity: 'blue',
        priceDrop: -20,
        link: 'http://kross.pl',
        image: 'http://localhost:3000/assets/prizes/Helmet1.jpg',
    },
    {
        name: 'Bike',
        rarity: 'purple',
        priceDrop: -999,
        link: 'http://kross.pl',
        image: 'http://localhost:3000/assets/prizes/Bike1.jpg',
    },
    {
        name: 'Bike wheel',
        rarity: 'green',
        priceDrop: -5,
        link: 'http://kross.pl',
        image: 'http://localhost:3000/assets/prizes/Wheel1.jpg',
    },
    {
        name: 'Bike helmet',
        rarity: 'blue',
        priceDrop: -20,
        link: 'http://kross.pl',
        image: 'http://localhost:3000/assets/prizes/Helmet3.jpg',
    },
    {
        name: 'Bike',
        rarity: 'purple',
        priceDrop: -999,
        link: 'http://kross.pl',
        image: 'http://localhost:3000/assets/prizes/Bike3.jpg',
    },
    {
        name: 'Bike wheel',
        rarity: 'green',
        priceDrop: -5,
        link: 'http://kross.pl',
        image: 'http://localhost:3000/assets/prizes/Wheel2.jpg',
    },
    {
        name: 'Bike helmet',
        rarity: 'blue',
        priceDrop: -20,
        link: 'http://kross.pl',
        image: 'http://localhost:3000/assets/prizes/Wheel1.jpg',
    },
    {
        name: 'Bike',
        rarity: 'purple',
        priceDrop: -999,
        link: 'http://kross.pl',
        image: 'http://localhost:3000/assets/prizes/Wheel1.jpg',
    },
    {
        name: 'Bike wheel',
        rarity: 'green',
        priceDrop: -5,
        link: 'http://kross.pl',
        image: 'http://localhost:3000/assets/prizes/Wheel1.jpg',
    },
    {
        name: 'Bike helmet',
        rarity: 'blue',
        priceDrop: -20,
        link: 'http://kross.pl',
        image: 'http://localhost:3000/assets/prizes/Wheel1.jpg',
    },
    {
        name: 'Bike',
        rarity: 'purple',
        priceDrop: -999,
        link: 'http://kross.pl',
        image: 'http://localhost:3000/assets/prizes/Wheel1.jpg',
    },
    {
        name: 'Bike wheel',
        rarity: 'green',
        priceDrop: -5,
        link: 'http://kross.pl',
        image: 'http://localhost:3000/assets/prizes/Wheel1.jpg',
    },
    {
        name: 'Bike helmet',
        rarity: 'blue',
        priceDrop: -20,
        link: 'http://kross.pl',
        image: 'http://localhost:3000/assets/prizes/Wheel1.jpg',
    },
    {
        name: 'Bike',
        rarity: 'purple',
        priceDrop: -999,
        link: 'http://kross.pl',
        image: 'http://localhost:3000/assets/prizes/Wheel1.jpg',
    },
    {
        name: 'Bike wheel',
        rarity: 'green',
        priceDrop: -5,
        link: 'http://kross.pl',
        image: 'http://localhost:3000/assets/prizes/Wheel1.jpg',
    },
    {
        name: 'Bike helmet',
        rarity: 'blue',
        priceDrop: -20,
        link: 'http://kross.pl',
        image: 'http://localhost:3000/assets/prizes/Wheel1.jpg',
    },
    {
        name: 'Bike',
        rarity: 'purple',
        priceDrop: -999,
        link: 'http://kross.pl',
        image: 'http://localhost:3000/assets/prizes/Wheel1.jpg',
    },
    {
        name: 'Bike wheel',
        rarity: 'green',
        priceDrop: -5,
        link: 'http://kross.pl',
        image: 'http://localhost:3000/assets/prizes/Wheel1.jpg',
    },
    {
        name: 'Bike helmet',
        rarity: 'blue',
        priceDrop: -20,
        link: 'http://kross.pl',
        image: 'http://localhost:3000/assets/prizes/Wheel1.jpg',
    },
    {
        name: 'Bike',
        rarity: 'purple',
        priceDrop: -999,
        link: 'http://kross.pl',
        image: 'http://localhost:3000/assets/prizes/Wheel1.jpg',
    },
    {
        name: 'Bike wheel',
        rarity: 'green',
        priceDrop: -5,
        link: 'http://kross.pl',
        image: 'http://localhost:3000/assets/prizes/Wheel1.jpg',
    },
    {
        name: 'Bike helmet',
        rarity: 'blue',
        priceDrop: -20,
        link: 'http://kross.pl',
        image: 'http://localhost:3000/assets/prizes/Wheel1.jpg',
    },
    {
        name: 'Bike',
        rarity: 'purple',
        priceDrop: -999,
        link: 'http://kross.pl',
        image: 'http://localhost:3000/assets/prizes/Wheel1.jpg',
    },
    {
        name: 'Bike wheel',
        rarity: 'green',
        priceDrop: -5,
        link: 'http://kross.pl',
        image: 'http://localhost:3000/assets/prizes/Wheel1.jpg',
    },
]